### PR TITLE
controlling rate of the refresh button

### PR DESCRIPTION
**Pull request by comountainclimber**
**What current issue(s) from Trello/Github does this address?**
https://github.com/CityOfZion/neon-wallet/issues/1021

**What problem does this PR solve?**

**How did you solve this problem?**
Requests can no be made until the current request is complete

**How did you make sure your solution works?**
Testing locally

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

### CODE REVIEW

**Comment by comountainclimber** [comment]
that solution is much better thanks 👍

**Comment by mhuggins** [comment]
@comountainclimber Looks like this needs to have single quotes changed to double quotes now that we merged the other PR.

**Comment by comountainclimber** [comment]
@mhuggins updated... still cant get `__tests__/components/Dashboard/AssetBalancesPanel.test.js` to pass either

**Comment by drptbl** [comment]
Issues found which are probably related to this PR:
#1079.

Also re-opened old issue:
#1021. 

It seems that this PR missed `TokenBalancesPanel.jsx` which is related to "Token Balances" section.

**Pull request merged**
