### PR TITLE
Add QuickVote Link

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) from Trello/Github does this address?**
https://github.com/CityOfZion/neon-wallet/issues/2475

**What problem does this PR solve?**
Adds a button to access QuickVote from the Tooltip

QuickVote Link

**How did you solve this problem?**
Used existing code to create the button.

**How did you make sure your solution works?**
`yarn dev` and updated the tests

**Are there any special changes in the code that we should be aware of?**
No.

**Is there anything else we should know?**
This is my first working solution. I used the `external` icon because I think that makes the most sense. I think placing the button right after the vote status makes sense but I am open to other suggestions.

- [x] Unit tests written?

To Do:
- [x]  Update Translations
- [x]  Does not render when logged into a legacy address
- [x]  Does not render for a watch only address
- [x]  Should follow light theme styles for light theme version

### CODE REVIEW

**Comment by comountainclimber** [comment]
Awesome work @jseagrave21 ! Functionally this is great however from a design and UI/UX and design perspective Im not sure this is going to work in its current form...

 Let me spend a bit brainstorming on how we can make this look and feel a little better

**Comment by jseagrave21** [comment]
> Awesome work @jseagrave21 ! Functionally this is great however from a design and UI/UX and design perspective Im not sure this is going to work in its current form...
> 
> Let me spend a bit brainstorming on how we can make this look and feel a little better

@comountainclimber sounds good. Thank you!

**Comment by comountainclimber** [comment]
@jseagrave21 so sorry for the super long delay here... Lets go ahead and implement the following:

image

NOTE:
- This should not render when logged into a legacy address
- Probably should not render for a watch only address as it will not work
- Should look follow light theme styles for light theme version

**Comment by jseagrave21** [comment]
@comountainclimber did you close this PR because you want me to make another PR implementing the improved design or because you already have the solution and are implementing it on a separate PR? If the latter is true, could you link the PR number here to reference?

**Comment by comountainclimber** [comment]
That was an accidental click sorry about that!

**Comment by jseagrave21** [comment]
@comountainclimber Okay, I think this is ready now. Sorry it took so long. Below are screenshots to validate the requirements you had. I didn't write any new unit tests because there isn't much functionality to test other than via live testing. I did change the link from "QuickVote" to Quickvote" to match the website. Also, I updated each translation with "Quickvote" because it is referencing a website so I didn't think it made sense to try to translate the title. Please let me know what you think.

Screenshot if the candidate falls out of the top 21:
If the candidate falls out

Screenshot of a legacy address:
Legacy

Screenshot of a watch address:
Watch Address

Screenshot of a normal N3 address with a vote:
With a vote

Screenshot of an address with no vote:
With No Vote

**Review by melanke — APPROVED** [review]

**Comment by jseagrave21** [comment]
@melanke Thanks! 🎉

**Pull request merged**
