### PR TITLE
CU-864ex6em8 - "Electron's Window Focus" when there is a new WcSdk re…

### PR DESCRIPTION
**Pull request by raulduartep**
…quest

**What current issue(s) from Trello/Github does this address?**

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

### CODE REVIEW

**Comment by lllwvlvwlll** [comment]
Task linked: [CU-864ex6em8 "Electron's Window Focus" when there is a new WcSdk request](https://app.clickup.com/t/864ex6em8)

**Review by melanke — APPROVED** [review]

**Comment by comountainclimber** [comment]
When I tested this on MacOS it was not working, the window did not focus when the app was minimized

**Review by melanke — APPROVED** [review]

**Comment by melanke** [comment]
@comountainclimber can you check again? Thanks

**Comment by comountainclimber** [comment]
@melanke @raulduartep how are you guys testing this I am a little confused... It still doesnt work on macOS when running `yarn dev` do I need to create a build?

**Review by comountainclimber — CHANGES_REQUESTED** [review]
As far as I can tell this does not work on MacOS

**Comment by comountainclimber** [comment]
There is still a bug on this branch as I have mentioned above and on discord, the app does not focus when clicking a connection prompt from `https://neon.coz.io/connect` this should be fixed before merging this PR

**Comment by melanke** [comment]
> There is still a bug on this branch as I have mentioned above and on discord, the app does not focus when clicking a connection prompt from https://neon.coz.io/connect this should be fixed before merging this PR

@comountainclimber I tested this on Windows and it's working on `dev` branch. It was made on another task.

**Pull request merged**
