### PR TITLE
Round Gas value down to prevent trying to oversell

### PR DESCRIPTION
**Pull request by hbibkrim**
**What current issue(s) from Trello/Github does this address?**
#59 

**What problem does this PR solve?**
Preventing users from trying to sell more gas than they own because displayed amount is rounded up

**How did you solve this problem?**
Using suggested solution

**How did you make sure your solution works?**
Manual test on Testnet

**Are there any special changes in the code that we should be aware of?**
Nope

**Is there anything else we should know?**
Nope

- [ ] Unit tests written?

### CODE REVIEW

**Comment by hbibkrim** [comment]
Or would you prefer to round gas down during initiateGetBalance?

**Comment by canesin** [comment]
This looks good @hbibkrim, if @Ejhfast don't give a opinion I will merge latter..

**Comment by Ejhfast** [comment]
looks good, I will merge once I do a quick independent test (do not like merging code without running myself), @canesin feel free to do so yourself if you have time

**Comment by Ejhfast** [comment]
thanks @hbibkrim! sorry about how slow i've been so slow on these

**Pull request merged**
