### PR TITLE
added SPOT to list of NEP5 Tokens'

### PR DESCRIPTION
**Pull request by daghdha**
**What current issue(s) from Trello/Github does this address?**
None, just adding a nep5 token for spotcoin.com.  We are on the mainnet and we have started our pre-ico already.

**What problem does this PR solve?**
SPOT not listed in the NEP5 token list.

**How did you solve this problem?**
Added the SPOT into the constants.js and as a comment in the ENDED_ICO_TOKEN.

**How did you make sure your solution works?**
I checked against previous NEP5 adds and did exactly the same thing. :) 

**Are there any special changes in the code that we should be aware of?**
no, just did what everyone else did. 

**Is there anything else we should know?**

- [ ] Unit tests written?
no.

### CODE REVIEW

**Comment by Ejhfast** [comment]
@daghdha are you a member of the project? can you provide proof this is a valid script hash for the project? I could not find it on the webpage

**Comment by daghdha** [comment]
hey!  yes, I am a member of this project, what kind of proof did you need
for it?  we could airdrop you a SPOT.  would that work for you?

**Comment by evgenyboxer** [comment]
@daghdha could you please resolve conflicts? after that I'll merge it to. Thank you,

**Comment by evgenyboxer** [comment]
@daghdha ?

**Comment by daghdha** [comment]
Argh. So sorry was sick and this dropped off the radar.  Will do it today
and if I can’t then I’ll cancel the pr

**Comment by daghdha** [comment]
@evgenyboxer done! sorry for the delay, I apologize.

**Pull request merged**
