### PR TITLE
Add option to save account NEP2 login screen

### PR DESCRIPTION
**Pull request by nickfujita**
**What problem does this PR solve?**
Users who have have a encrypted key that was not created in neon-wallet or imported via JSON, need to have an easy option to allow them to save their account when logging in.

**How did you solve this problem?**
Added an options to set a account name, and save the account upon logging in.

**How did you make sure your solution works?**
- Naivigate to "Login using an encrypted key"
- Enter passphrase and encrypted key
- Check the option for save account
- Enter a account label
- Login
- If successful, you will be taken to the normal account dashbaord

Corner cases
- If the user already saved this encrypted key, it will simply ignore the new label, and log in the user
- If the user enters a label that is conflicting with one that is already saved, it will show them an error notification

### CODE REVIEW

**Comment by drptbl** [comment]
@nickfujita Thanks.

Looks like it doesn't save new account for me. Tested on Windows 10.

save_key

**Comment by nickfujita** [comment]
@drptbl fixed

**Comment by drptbl** [comment]
@nickfujita Everything works great here 👍.

Would it be hard to add this message if account has been saved with success?
acc_saved

This message show up if account was saved with success after saving it on new wallet creation.

**Comment by nickfujita** [comment]
Added `Account saved!` notification.

**Comment by drptbl** [comment]
Re-tested, works fine, thank you.

**Comment by Ashleygross** [comment]
Needs little bit more

**Pull request merged**
