### PR TITLE
initital refactor of component and container architecture

### PR DESCRIPTION
**Pull request by dvdschwrtz**
**What current issue(s) from Trello/Github does this address?**

Start to refactor the container and component architecture and move more logic into the actions/ modules files.

**What problem does this PR solve?**

Refactoring the neon wallet

**How did you solve this problem?**

creating a new container folder structure with an index.js connect wrapper and its corresponding .jsx file

**How did you make sure your solution works?**

I QA tested it a bit. further review and QA testing of the login with private key and then sending from the dashboard function would be great!

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

### CODE REVIEW

**Comment by dvdschwrtz** [comment]
@evgenyboxer please review and let me know what you think of the way I implemented the changes. Also, I added flow to some of the modules files that I modified when pulling logic out of the containers. I don't know if this is correct or not, as the modules files do not have flow incorporated into them already.

**Comment by evgenyboxer** [comment]
Looks really good! Good job! +1 for Flow in modules too.

The only thing I would change is the usage of Wrapper (DashboardWrapper).
I think it’s okay to use it without Wrapper and do a default export connect(...) in the containers without a dedicated const for it.

What do you think?

**Comment by dvdschwrtz** [comment]
Thanks! Appreciate the review. I made the change. should be good to go now.

**Comment by evgenyboxer** [comment]
Cheers.
By the way, I believe that you don’t need the ‘/index’ in the end of the import.
‘containers/Dashboard’ should lead to the index.js file without /index

**Pull request merged**
