### PR TITLE
Added DeepBrain Coin

### PR DESCRIPTION
**Pull request by mhuggins**
**What current issue(s) from Trello/Github does this address?**
N/A

**What problem does this PR solve?**
It supports sending & showing balance for DBC (DeepBrain Coin), similar to RPX.

**How did you solve this problem?**
I added the MainNet & TestNet constants for the DBC hash.

**How did you make sure your solution works?**
I loaded the wallet and confirmed that I can view the 0 DBC balance & view DBC token information by clicking on the balance.  **NOTE:** I was unable to test transferring DBC due to having a 0 balance.

**Are there any special changes in the code that we should be aware of?**
N/A

**Is there anything else we should know?**
See **NOTE** above.

- [x] Unit tests written?

### CODE REVIEW

**Comment by mhuggins** [comment]
The test failure doesn't appear to relate to my change.

**Comment by slipo** [comment]
Just fyi: I had the same issue with the build. Here was my fix: https://github.com/CityOfZion/neon-wallet/pull/444/commits/bfe2090bca73e396884f626c8ecc8645ef7dd570

**Comment by mhuggins** [comment]
@slipo Thanks, rebasing against `dev` fixed it!

**Comment by ministoat** [comment]
Using a ledger I cannot send dbc with this version, error message says not supported

**Comment by mhuggins** [comment]
@ministoat I don't have a ledger to test against.  I will have to see if someone else can help out.

**Pull request merged**
