### PR TITLE
Website Enhancements

### PR DESCRIPTION
**Pull request by comountainclimber**
**What current issue(s) from Trello/Github does this address?**
https://github.com/CityOfZion/neon-wallet/issues/247

**Is there anything else we should know?**
There is a small development build behind this leveraging webpack here is the repo:
https://github.com/comountainclimber/neon-wallet-website

view the deployed version here: https://comountainclimber.github.io/neon-wallet-website/

### CODE REVIEW

**Comment by comountainclimber** [comment]
:smiley_cat:

**Comment by slipo** [comment]
Big improvement in my opinion! Nice work.

**Comment by comountainclimber** [comment]
@slipo my pleasure... Looking forward to contributing more to this project. Is there anything I need to do on my end to get this thing deployed?

**Comment by comountainclimber** [comment]
@evgenyboxer If you have any questions let me know... Its basically a very simple jQuery app. Using webpack to hash the CSS and JS files (having these hashed should ensure that clients will always get updated code) as well as for vendor prefixing all of the CSS. I mostly wanted to use webpack because I am so used to reloading dev server :D

**Comment by Nat1988** [comment]
@comountainclimber Hi buddy. First off, thank you for your contribution! It is very much appreciated and a great start!

So, from a design and user-experience perspective this needs a little work from my eye just to help consolidate some of the information and to bring it in line with the branding of NEON/CoZ. I have attached a quick mock-up that I created last night to give an example of where we see the NEON wallet website in the future. This design will evolve as the wallet evolves but for now I feel a quick landing page would serve best.
concept_02


If you like, we can collaborate together on this, or I could provide designs + assets for build.

~Velocihamster

**Comment by comountainclimber** [comment]
I asked in the issue thread if you guys had mock ups or something specific and even went through the trouble of creating one to generate feedback. After all the work I put in and after receiving no feedback until now I will not be starting from scratch to redo everything. Good luck on the new site.

**Comment by dvdschwrtz** [comment]
@comountainclimber sorry about that. I know everyone is really busy, but it seems you do have a point about posting the mockups and then getting feedback to change it later. This is an open source project so you have lots of people working on it. I think Velocihamster is the only designer or one of the only designers at the moment, so he probably never saw it til now and found a way to improve it. I personally like the new design he posted a lot and I suspect you would agree that it looks pretty good. We can take care of changing the site if you are not interested, but I hope that you keep contributing. NEO is a  great project if you are interested in learning the blockchain and working with smart people. I suspect if you asked a code related question there would have been more feedback.

**Comment by Nat1988** [comment]
@comountainclimber Sorry, this is the first chance I have had to reply. @dvdschwrtz is correct in the fact that the first time I was made aware of this was about 16 hours ago so I had not previously seen your mock-up and comments otherwise a design would have been put forward before any dev work happened - I do apologise for this. Historically designers tend not to use GitHub so this was missed. I would also like to re-iterate David's point above that if you're not interested in continuing the website development that I hope you keep contributing towards NEO as we need eager and talented people to make that difference.

**Comment by Ejhfast** [comment]
@comountainclimber your effort was not wasted, it helped inspire @Nat1988's revised design! there was no mockup at the time, many things were/are on backlog. we really appreciate your effort, and CoZ council will certainly reward you for the work you put in

we would love if you continued to help with this, perhaps working with @Nat1988 to iterate on a final design

**Comment by comountainclimber** [comment]
I appreciate the kind words and apologize for my frustration earlier... I understand that contributors are very busy. If you guys are psyched on this mock up than I can code it over the next day or two. @Nat1988 I definitely like what you have going on here. These are all assets I currently have access to so no need to upload anything.

@Nat1988 @Ejhfast  Please let me know if you guys have any other major concerns/design features you would like incorporated into the new site

**Comment by Nat1988** [comment]
@comountainclimber No worries buddy. I know myself the frustration of designing something only to have to start again so please accept my sincerest apologies again for jumping in late on this - it's great to have you back on board 💯!

So RE the designs: tomorrow I'll jump back on this to tweak/refine the proposed design as this was a quick mockup (it won't change much - just a few alignments here and there), and then I'll create tablet/mobile designs as well. I think the only asset you'll need will be the laptop with the wallet mockup. However I am currently sourcing a better screenshot for this as it would be good to have a wallet UI that has transactions/assets rather than the current empty one.

Regarding anything extra, I think for now we won't need any other design features other than a model state for the QR codes which I will also provide a design for. @Ejhfast can you confirm please? :)

**Comment by Ejhfast** [comment]
@Nat1988 @comountainclimber yes, that all sounds great :)

(i provided @Nat1988 with a better screenshot, so now should have everything you need)

**Comment by comountainclimber** [comment]
@Nat1988 there is one tiny other detail - the linux version has two builds. Can you be sure to incorporate that into your mock up. Including the modal qr code mock up would help a ton as well. 
Let me know when you have finished the laptop/screenshot asset and where I can download the file. thanks guys

**Comment by comountainclimber** [comment]
https://comountainclimber.github.io/neon-website/ using a placeholder for the screen shot asset until I get one from @Nat1988 will also build out the modals and responsive layouts when I get those mock ups

**Comment by Nat1988** [comment]
@comountainclimber Nice work so far bud!

So for the Linux download, what is the difference between the 2 builds so I can ensure this is communicated in the design?

I'm starting on the tablet/mobile/modal designs now so I should have these to you in the next hour or 2.

~Hamster

**Comment by comountainclimber** [comment]
@Nat1988 it's just the file extension. Check out the current neonwallet.com

**Comment by canesin** [comment]
@comountainclimber please join our slack [clicking here](https://slack-helper.cityofzion.io/invite/T656BRXQ8) we have a design channel that is always looking for talent.

**Comment by comountainclimber** [comment]
@canesin will join the slack in a terrible designer though 😂 Mostly a react/JavaScript developer

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neon-wallet/pull/300

**Pull request closed without merging**
