### PR TITLE
added comma delimination to NEO-USD live display

### PR DESCRIPTION
**Pull request by db383**
Added comma separation to live USD display.
Original: $12345.78 -> Now: $12,345.78

### CODE REVIEW

**Comment by Ejhfast** [comment]
sorry for the delay on this, but could you update to use the cmc api (we swapped bittrex for that in master)

**Comment by db383** [comment]
Updated NEO - USD conversion query from using two bittrex api queries to a single coinmarketcap api query.

**Comment by Ejhfast** [comment]
hey sorry for confusion, so the api has been moved to neon-js, which is now an import. can you pull there instead? thanks!

**Comment by Ejhfast** [comment]
i didn't notice right away as you were pull requesting to alpha-release branch

**Pull request closed without merging**
