### PR TITLE
Small cleanup of repository and minor README changes

### PR DESCRIPTION
**Pull request by golivera**
**What current issue(s) from Trello/Github does this address?**
None

**What problem does this PR solve?**
Removes build files and MacOS unnecessary files. Small update to `README.md`.

**How did you solve this problem?**
Add the filename and foldernames to `.gitignore`. Removed the files and minor text update to `README.md`

**How did you make sure your solution works?**
Started at this "clean" state and ran the install and build process. Successfully logged into the application.

**Are there any special changes in the code that we should be aware of?**
No.

**Is there anything else we should know?**
No.

- [x] Unit tests written? N/A

### CODE REVIEW

**Comment by Ejhfast** [comment]
looks great, thanks!

**Comment by Ejhfast** [comment]
@golivera we actually need the build directory that you removed to stay here, it contains the icon asset setup for electron-builder, realized this when I tried to rebuild. adding it back now

**Comment by golivera** [comment]
@Ejhfast Thanks for the heads up. What steps should I have taken to find this problem? 🤔

**Comment by Ejhfast** [comment]
If you had tried to rebuild might have noticed, but definitely no big deal

**Pull request merged**
