### PR TITLE
 Show wallet gas and total value, show neo/gas prices

### PR DESCRIPTION
**Pull request by slipo**
**What current issue(s) from Trello/Github does this address?**
None

**What problem does this PR solve?**
Currently the app just shows the NEO wallet value and excludes GAS.

**How did you solve this problem?**
Now the app will show the quoted NEO/GAS prices and the NEO/GAS wallet values as four separate data items. In addition it shows a sum total wallet value.

**How did you make sure your solution works?**
There are automated tests. I also manually checked the app to see the values.

**Are there any special changes in the code that we should be aware of?**
It's switching from bittrex API to coinmarketcap because the latter has the GAS USD market.

**Is there anything else we should know?**

- [x] Unit tests written?
yes!

### CODE REVIEW

**Comment by shawnmclean** [comment]
usd gas

I'm approving the code, the design, I'm not sure if anyone else wants to give any feedback on that.

**Comment by evgenyboxer** [comment]
PR looks good.
I’m terms of the design, I think it’s better to drop the value of a single Neo/Gas.

Under each asset just write the total, without the wording “NEO/GAS Wallet”, as it is inferred from the context.

I agree that having a total for both is a good idea. In terms of the wording, maybe instead of “Wallet”, just “Total”.

**Comment by slipo** [comment]
Is this what we're looking for? If so I'll push it out.

designchangesneon

**Comment by slipo** [comment]
OK, those changes were looking pretty good to me so I pushed them out. Let me know if there's anything else to do.

**Comment by shawnmclean** [comment]
Looks much cleaner!

**Pull request merged**
