### PR TITLE
CircleCI Workflows and Yarn

### PR DESCRIPTION
**Pull request by shawnmclean**
**What current issue(s) from Trello/Github does this address?**
CI

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

### CODE REVIEW

**Comment by Ejhfast** [comment]
hey @shawnmclean, going through active PRs now, what does this add to CI workflow?

**Comment by shawnmclean** [comment]
@Ejhfast It sets up the structure to use workflows so we can add in automated deployment later (via manual trigger or continuous)

**Comment by Ejhfast** [comment]
is there a way to do this without changing `start` to `webpack && electron`?, I'd like to continue to use the `webpack watch` in the background, combined with `npm start`?

**Comment by shawnmclean** [comment]
@Ejhfast removed the package.json changes.

**Pull request merged**
