### PR TITLE
Use password type for the private key field for security reason

### PR DESCRIPTION
**Pull request by marcdelalonde**
**What current issue(s) from Trello/Github does this address?**
Some user feedbacks

**What problem does this PR solve?**
Security issues

**How did you solve this problem?**
Change the html field type

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**

- [ ] Unit tests written?

### CODE REVIEW

**Comment by darfraider** [comment]
You need to make the changes in both login forms right?  Encrypted Key login and Private Key login?  I think that would be a good idea.

**Comment by Satoshinaire** [comment]
I think the main benefit of this change is psychological more than anything. But that's not nothing.

Agree too that if you're going to do it, you should do it everywhere that makes sense.

**Comment by darfraider** [comment]
It’s interesting that this PR is not merged into the master but when I cloned the master and built it, when I ran it, the encrypted key login ad well as private key login enters fields are shadowed with *. Not sure where this is handled because the html code inserted in the js methods are still input type of “text” (instead of “psssword” as proposed by this PR).

**Comment by Ejhfast** [comment]
This is on the roadmap, but with support for a toggle -- some people are copying from paper wallets and want to see the key as they type in.

If you add this feature to all non-password inputs turned off/on by a toggle, would be happy to accept!

**Comment by shawnmclean** [comment]
Solved in #69

**Pull request closed without merging**
