### PR TITLE
E2e circle integration tests

### PR DESCRIPTION
**Pull request by shawnmclean**

### CODE REVIEW

**Comment by thuansb** [comment]
Hi @shawnmclean, I think we have to install Chrome on CircleCI to be able to run the test with Xvfb

**Comment by shawnmclean** [comment]
@thuansb is there any other commands I'd need to run? I'm using a docker container with the following description:
`builder:wine-chrome — google-chrome-stable and xvfb are available — you can use this image for headless testing of Electron application. Based on builder:wine.`

**Comment by thuansb** [comment]
@shawnmclean we need to start Xvfb before run the test, let me check that and let you know soon

**Comment by thuansb** [comment]
@shawnmclean: I try with these commands below, it able to run the test now but there are no test pass. I don't know why. All the test cases are passed when run on local. Do you know anyway to debug that? (e.g. setup CircleCI on local machine)
`      - run: export DISPLAY=:99
      - run: Xvfb &
      - run: sleep 3 # give xvfb some time to start
      - run: yarn assets
      - run: yarn test:e2e
`

**Comment by dvdschwrtz** [comment]
@thuansb it looks like my tests are failing on CircleCI but passing on local as well. It might be related to this error I am getting after all the tests pass
```/Users/davidschwartz/dev/neon-wallet/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

I am going to be looking at the new ledger code today. If you are investigating CircleCI I think this might be helpful

**Comment by thuansb** [comment]
@shawnmclean: I'm able to run successfully the e2e test script with below config:

```
      - run: yarn assets
      ....
      .... 
      - run: Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
      - run: export DISPLAY=:99
      - run: sleep 3 # give xvfb some time to start
      - run: yarn test:e2e
```

**Comment by thuansb** [comment]
@shawnmclean: Finally it's works with below commands:

```
      - run: yarn
      - run: yarn assets
      - run:
          name: Running Xvfb
          command: Xvfb -ac :99 -screen 0 1280x1024x16
          background: true
      - run:
          name: Run Tests
          command: |
            export DISPLAY=:99
            yarn test:e2e
```

**Comment by shawnmclean** [comment]
@thuansb I'm also having a hard time getting it to pass. Would you mind making a PR with the circle changes?

**Comment by thuansb** [comment]
Sure @shawnmclean I created PR #280

**Pull request closed without merging**
