### PR TITLE
App Redesign (Part 1)

### PR DESCRIPTION
**Pull request by mhuggins**
**What current issue(s) from Trello/Github does this address?**
N/A

**What problem does this PR solve?**
It starts to implement the designs provided by @asalib.

neon-wallet

**How did you solve this problem?**
* Replaced the `Header` with new `Sidebar` component.
* Replaced the `Footer` with a temporary place to switch networks.  (Need to coordinate with Alf how this should work long term.)
* Fixed routing to allow for proper active `NavLink` highlighting.
* Added generic `Panel` component.
* Added `AssetBalancesPanel` component.
* Added `TokenBalancesPanel` component.
* Added `TransactionHistoryPanel` component, and separated transaction history into its own screen.
* Added sidebar links for sending, receiving, and participating in token sales that temporarily lead to their existing modals.

**How did you make sure your solution works?**
I smoke tested as best as I could.  I also updated the test suite.

**Are there any special changes in the code that we should be aware of?**
N/A

**Is there anything else we should know?**
N/A

- [x] Unit tests written?

### CODE REVIEW

**Comment by Melicio** [comment]
Add nep5 $ Balance?

**Comment by mhuggins** [comment]
I'll mention it to the designer.

**Comment by asalib** [comment]
Token $ balances will be shown in the bottom right window

image

**Comment by Melicio** [comment]
That is amazing! Your a hero! 🙌🙀🙌

**Comment by mhuggins** [comment]
Closing in favor of #663 that merges into a new `design-v2` branhc.

**Pull request closed without merging**
