### PR TITLE
Feature/delete website assets

### PR DESCRIPTION
**Pull request by comountainclimber**
All of these files including the automatic deployment pipeline can be found here https://github.com/CityOfZion/neon-wallet-website

**What current issue(s) from Trello/Github does this address?**
https://github.com/CityOfZion/neon-wallet/issues/635

**What problem does this PR solve?**

**How did you solve this problem?**

**How did you make sure your solution works?**

**Are there any special changes in the code that we should be aware of?**

**Is there anything else we should know?**
The directory containing the sketch assets in https://github.com/CityOfZion/neon-wallet-website is called `/design`

- [ ] Unit tests written?

### CODE REVIEW

**Comment by mhuggins** [comment]
I think we just need the last commit here.  I think you could fix this by doing this:

```
git checkout dev
git fetch --all
git rebase upstream/dev
git push origin dev --no-verify
git checkout -b feature/delete-website-assets-redo
git cherry-pick b640faeebb2add62504093b17a183d0e9c10b2f9
git push origin feature/delete-website-assets-redo
```

**Comment by mhuggins** [comment]
Please correct me if I'm wrong about only needing the last commit. 😄

**Comment by mhuggins** [comment]
We should check with @dvdschwrtz if this is more appropriate to go into the `rebase` branch as well.  I'm not sure what the state of that is.

**Comment by mhuggins** [comment]
Might hold off on this, I'm not sure what the status of dvdschwrtz's `rebase` branch is.  His goal is to force push that branch onto the `dev` branch I think.

**Comment by comountainclimber** [comment]
Thanks @mhuggins I will rebase and submit a separate PR definitely dont want all of this nonsense in the commit history

**Pull request closed without merging**
