### PR TITLE
Moved batch actions separate files

### PR DESCRIPTION
**Pull request by alexhulbert**
**What current issue(s) from Trello/Github does this address?**
None. It fixes a lot of ```//TODO```s though

**What problem does this PR solve?**
Batch actions were being created within index.js files

**How did you solve this problem?**
As instructed by the ```//TODO``` comments, I moved everything into its own file under app/actions.

**How did you make sure your solution works?**
I tried running the wallet. All the modified components still load correctly

### CODE REVIEW

**Comment by evgenyboxer** [comment]
@alexhulbert Build failing on CI, can you try to build locally and see if you got any errors?

**Comment by alexhulbert** [comment]
@evgenyboxer I accidentally made all these changes in my branch for the last pull request. I had to do some git yoga to move everything over to a new feature-* branch and I must have lost a file or two while doing that. I thought for sure I tested the code afterward, though. I'll go ahead and fix everything.

**Comment by alexhulbert** [comment]
@evgenyboxer Looks like the issue is happening on the design-v2 branch as well as my fork. It seems as though the issue is unrelated to this particular pull request. I've created a relevant issue (#1214) and assigned myself

**Comment by alexhulbert** [comment]
The build failed message can be safely ignored at this point. The error in Circle is irrelevant to the code in this PR. Another PR fixing the build issues has been submitted independently of this one.

**Pull request merged**
