### PR TITLE
Updated MacOS toolbar

### PR DESCRIPTION
**Pull request by hbibkrim**
**What current issue(s) from Trello/Github does this address?**
#27 

**What problem does this PR solve?**
#27 

**How did you solve this problem?**
Removed Reload submenu item - shortcut no longer as a result.

**How did you make sure your solution works?**
Tested on MacOS Sierra

**Are there any special changes in the code that we should be aware of?**
Removed few other submenu items and added links to CoZ/Github/Slack/Reddit (could remove if unnecessary).

**Is there anything else we should know?**
Windows/Linux should be unaffected but as I only have a Mac, I can only test on that.
The most minimalistic a Menu can have is Neon menu item with nothing inside it. I've left the basic commands and the link to Dev tools. In future PR, can display Toggle Dev Tools only when running in debug mode?

- [ ] Unit tests written?

### CODE REVIEW

**Comment by marksuman** [comment]
Would it be better to get the Reload functionality to work instead of removing the option from the menu?

**Comment by hbibkrim** [comment]
I don't think the reload functionality brings anything to the application that logging out doesn't. It looked like boilerplate code left over and not an intentional feature

**Comment by danielfm123** [comment]
You can use that neo web wallet https://www.myneowallet.io

**Comment by canesin** [comment]
@CityOfZion/council someone with OSX to test ?

**Comment by Ejhfast** [comment]
thanks @hbibkrim!

**Pull request merged**
